/**
 * Catalogue of Bot API methods, grouped the way the official docs group them.
 * Used by the API console so every method is reachable, including ones that
 * have no dedicated UI.
 */
export interface MethodGroup {
  name: string;
  methods: string[];
}

export const METHOD_GROUPS: MethodGroup[] = [
  {
    name: "Getting updates",
    methods: ["getUpdates", "setWebhook", "deleteWebhook", "getWebhookInfo"],
  },
  {
    name: "Available methods",
    methods: [
      "getMe",
      "logOut",
      "close",
      "sendMessage",
      "forwardMessage",
      "forwardMessages",
      "copyMessage",
      "copyMessages",
      "sendPhoto",
      "sendLivePhoto",
      "sendAudio",
      "sendDocument",
      "sendVideo",
      "sendAnimation",
      "sendVoice",
      "sendVideoNote",
      "sendPaidMedia",
      "sendMediaGroup",
      "sendLocation",
      "sendVenue",
      "sendContact",
      "sendPoll",
      "sendChecklist",
      "sendDice",
      "sendMessageDraft",
      "sendChatAction",
      "setMessageReaction",
      "getUserProfilePhotos",
      "getUserProfileAudios",
      "setUserEmojiStatus",
      "getFile",
    ],
  },
  {
    name: "Chat & member management",
    methods: [
      "banChatMember",
      "unbanChatMember",
      "restrictChatMember",
      "promoteChatMember",
      "setChatAdministratorCustomTitle",
      "setChatMemberTag",
      "banChatSenderChat",
      "unbanChatSenderChat",
      "setChatPermissions",
      "exportChatInviteLink",
      "createChatInviteLink",
      "editChatInviteLink",
      "createChatSubscriptionInviteLink",
      "editChatSubscriptionInviteLink",
      "revokeChatInviteLink",
      "approveChatJoinRequest",
      "declineChatJoinRequest",
      "answerChatJoinRequestQuery",
      "sendChatJoinRequestWebApp",
      "setChatPhoto",
      "deleteChatPhoto",
      "setChatTitle",
      "setChatDescription",
      "pinChatMessage",
      "unpinChatMessage",
      "unpinAllChatMessages",
      "leaveChat",
      "getChat",
      "getChatAdministrators",
      "getChatMemberCount",
      "getChatMember",
      "getUserPersonalChatMessages",
      "setChatStickerSet",
      "deleteChatStickerSet",
      "getUserChatBoosts",
      "getBusinessConnection",
      "answerGuestQuery",
      "getManagedBotToken",
      "replaceManagedBotToken",
      "getManagedBotAccessSettings",
      "setManagedBotAccessSettings",
    ],
  },
  {
    name: "Forum topics",
    methods: [
      "getForumTopicIconStickers",
      "createForumTopic",
      "editForumTopic",
      "closeForumTopic",
      "reopenForumTopic",
      "deleteForumTopic",
      "unpinAllForumTopicMessages",
      "editGeneralForumTopic",
      "closeGeneralForumTopic",
      "reopenGeneralForumTopic",
      "hideGeneralForumTopic",
      "unhideGeneralForumTopic",
      "unpinAllGeneralForumTopicMessages",
    ],
  },
  {
    name: "Bot profile",
    methods: [
      "setMyCommands",
      "deleteMyCommands",
      "getMyCommands",
      "setMyName",
      "getMyName",
      "setMyDescription",
      "getMyDescription",
      "setMyShortDescription",
      "getMyShortDescription",
      "setMyProfilePhoto",
      "removeMyProfilePhoto",
      "setChatMenuButton",
      "getChatMenuButton",
      "setMyDefaultAdministratorRights",
      "getMyDefaultAdministratorRights",
    ],
  },
  {
    name: "Updating messages",
    methods: [
      "editMessageText",
      "editMessageCaption",
      "editMessageMedia",
      "editMessageLiveLocation",
      "stopMessageLiveLocation",
      "editMessageReplyMarkup",
      "editMessageChecklist",
      "editEphemeralMessageText",
      "editEphemeralMessageMedia",
      "editEphemeralMessageCaption",
      "editEphemeralMessageReplyMarkup",
      "stopPoll",
      "approveSuggestedPost",
      "declineSuggestedPost",
      "deleteMessage",
      "deleteMessages",
      "deleteEphemeralMessage",
      "deleteMessageReaction",
      "deleteAllMessageReactions",
      "answerCallbackQuery",
    ],
  },
  {
    name: "Stickers",
    methods: [
      "sendSticker",
      "getStickerSet",
      "getCustomEmojiStickers",
      "uploadStickerFile",
      "createNewStickerSet",
      "addStickerToSet",
      "setStickerPositionInSet",
      "deleteStickerFromSet",
      "replaceStickerInSet",
      "setStickerEmojiList",
      "setStickerKeywords",
      "setStickerMaskPosition",
      "setStickerSetTitle",
      "setStickerSetThumbnail",
      "setCustomEmojiStickerSetThumbnail",
      "deleteStickerSet",
    ],
  },
  {
    name: "Inline mode",
    methods: [
      "answerInlineQuery",
      "answerWebAppQuery",
      "savePreparedInlineMessage",
      "savePreparedKeyboardButton",
    ],
  },
  {
    name: "Payments & Stars",
    methods: [
      "sendInvoice",
      "createInvoiceLink",
      "answerShippingQuery",
      "answerPreCheckoutQuery",
      "getMyStarBalance",
      "getStarTransactions",
      "refundStarPayment",
      "editUserStarSubscription",
    ],
  },
  {
    name: "Gifts & verification",
    methods: [
      "getAvailableGifts",
      "sendGift",
      "giftPremiumSubscription",
      "verifyUser",
      "verifyChat",
      "removeUserVerification",
      "removeChatVerification",
    ],
  },
  {
    name: "Business accounts",
    methods: [
      "readBusinessMessage",
      "deleteBusinessMessages",
      "setBusinessAccountName",
      "setBusinessAccountUsername",
      "setBusinessAccountBio",
      "setBusinessAccountProfilePhoto",
      "removeBusinessAccountProfilePhoto",
      "setBusinessAccountGiftSettings",
      "getBusinessAccountStarBalance",
      "transferBusinessAccountStars",
      "getBusinessAccountGifts",
      "getUserGifts",
      "getChatGifts",
      "convertGiftToStars",
      "upgradeGift",
      "transferGift",
      "postStory",
      "repostStory",
      "editStory",
      "deleteStory",
    ],
  },
  {
    name: "Rich messages",
    methods: ["sendRichMessage", "sendRichMessageDraft"],
  },
  {
    name: "Telegram Passport & games",
    methods: ["setPassportDataErrors", "sendGame", "setGameScore", "getGameHighScores"],
  },
];

export const ALL_METHODS = METHOD_GROUPS.flatMap((g) => g.methods);

/** Starter payloads for the console, so a method never opens on a blank page. */
export const METHOD_TEMPLATES: Record<string, unknown> = {
  sendMessage: { chat_id: 0, text: "Hello", parse_mode: "MarkdownV2" },
  sendMessageDraft: { chat_id: 0, draft_id: 1, text: "Thinking…" },
  sendRichMessage: {
    chat_id: 0,
    rich_message: {
      html: "<h2>Rich message</h2><p>Hello <b>from Humanoid</b>.</p><hr/><blockquote>Interactive, structured, and native.</blockquote>",
    },
  },
  sendRichMessageDraft: {
    chat_id: 0,
    draft_id: 1,
    rich_message: { html: "<tg-thinking>Thinking…</tg-thinking>" },
  },
  sendChatAction: { chat_id: 0, action: "typing" },
  answerCallbackQuery: { callback_query_id: "", text: "Done", show_alert: false },
  answerInlineQuery: {
    inline_query_id: "",
    results: [
      {
        type: "article",
        id: "1",
        title: "Result",
        input_message_content: { message_text: "Hello from inline mode" },
      },
    ],
    cache_time: 0,
    is_personal: true,
  },
  setMyCommands: {
    commands: [{ command: "start", description: "Start the bot" }],
    scope: { type: "default" },
  },
  setWebhook: {
    url: "https://example.com/webhook",
    allowed_updates: ["message", "callback_query"],
    drop_pending_updates: false,
  },
  createChatInviteLink: { chat_id: 0, name: "Link", creates_join_request: false },
  promoteChatMember: {
    chat_id: 0,
    user_id: 0,
    can_delete_messages: true,
    can_pin_messages: true,
  },
  restrictChatMember: {
    chat_id: 0,
    user_id: 0,
    permissions: { can_send_messages: false },
    until_date: 0,
  },
  createInvoiceLink: {
    title: "Item",
    description: "An item",
    payload: "payload",
    currency: "XTR",
    prices: [{ label: "Item", amount: 100 }],
  },
  getStarTransactions: { offset: 0, limit: 20 },
  createNewStickerSet: {
    user_id: 0,
    name: "set_name_by_yourbot",
    title: "My set",
    stickers: [{ sticker: "file_id_or_url", format: "static", emoji_list: ["😀"] }],
  },
  savePreparedInlineMessage: {
    user_id: 0,
    result: {
      type: "article",
      id: "1",
      title: "Prepared",
      input_message_content: { message_text: "Hi" },
    },
    allow_user_chats: true,
  },
  sendGift: { user_id: 0, gift_id: "" },
  getUserPersonalChatMessages: { user_id: 0, limit: 20 },
  getManagedBotToken: { user_id: 0 },
  getManagedBotAccessSettings: { user_id: 0 },
};
